export const initializeDatabase = `
CREATE TABLE $1(
  ID INT PRIMARY KEY NOT NULL,
  MESSAGE_COUNT INT NOT NULL,
  REACTION_COUNT INT NOT NULL,
  VOCAL_TIME REAL NOT NULL,
  STREAMING_TIME REAL NOT NULL,
  WATCHING_TIME REAL NOT NULL,
  ADDRESS CHAR(42)
);
`
export const incrementMessageCountQuerry = 
`
UPDATE $1 
  SET $3 = $3 + 1
WHERE id = $2;
`


