// autogenerated by sql-generate v1.5.0 on Sun Jun 13 2021 17:28:51 GMT+0200 (Central European Summer Time)

var sql = require('sql');


/**
 * SQL definition for public.messages
 */
exports.messages = sql.define({
	name: 'messages',
	columns: [
		{ name: 'id' },
		{ name: 'userid' },
		{ name: 'set' }
	]
});


/**
 * SQL definition for public.users
 */
exports.users = sql.define({
	name: 'users',
	columns: [
		{ name: 'id' },
		{ name: 'address' }
	]
});


